title: zzz
frequency: 3
dirfilter:
- tmp
- .git
- .github
- scripts
- vendor
- logs
- assets
- .github
- data
ext:
- go
- js
- tmpl
- ini
enablerun: true
action:
  before:
  - find . -name ".DS_Store" -print -delete
  - rm -rf logs/run_away.log
  - go generate internal/assets/conf/conf.go
  - go generate internal/assets/public/public.go
  - go generate internal/assets/templates/templates.go
  after:
  - ps -ef|grep 'mail-server service'| grep -v grep | awk '{print $2}' | xargs kill -9
  -  ./mail-server service &
  exit:
  - ps -ef|grep 'mail-server service'| grep -v grep
  - ps -ef|grep 'mail-server service'| grep -v grep | awk '{print $2}' | xargs kill -9
  - rm -rf ./mail-server
